version: '3.8'

services:
  # Main pipeline service
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traveltools-pipeline
    volumes:
      - ./data:/app/data:Z
      - ./outputs:/app/outputs:Z
    stdin_open: true
    tty: true
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    command: python -m travel_tools.launcher

  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: traveltools-dev
    volumes:
      - ./src:/app/src:Z
      - ./tests:/app/tests:Z
      - ./data:/app/data:Z
      - ./outputs:/app/outputs:Z
      - ./config:/app/config:Z
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    command: /bin/bash

  # Testing service
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: traveltools-test
    volumes:
      - ./src:/app/src:Z
      - ./tests:/app/tests:Z
    command: pytest -v --cov

  # Web server
  webserver:
    image: docker.io/library/python:3.11-slim
    container_name: traveltools-webserver
    volumes:
      - ./outputs:/app/outputs:Z
    working_dir: /app/outputs
    ports:
      - "8080:8000"
    command: python -m http.server 8000
